location = /dicionario-vocabulario {
    return 301 https://$host/dicionario-vocabulario/;
}

# Deve surgir antes da localização pública, por ser mais específica.
location = /dicionario-vocabulario/editor {
    return 301 https://$host/dicionario-vocabulario/editor/;
}

location ^~ /dicionario-vocabulario/editor/ {
    proxy_pass http://10.10.10.99:5060/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 60s;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
}

location ^~ /dicionario-vocabulario/ {
    proxy_pass http://10.10.10.99:5059/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_connect_timeout 60s;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
}
