const $ = selector => document.querySelector(selector);
const editorialBasePath = (document.querySelector('meta[name="acl-editor-base-path"]')?.content || "").replace(/\/+$/, "");
let overviewData = null;
let selectedId = null;
let selectedEntry = null;
let controlledValues = [];
let publicationItems = [];
let publicationTimer = null;
let entryOffset = 0;
let activeAlphabet = "";

function apiUrl(path) { const value = path.startsWith("/") ? path : `/${path}`; return `${editorialBasePath}${value}` || "/"; }
function publicUrl(path) { const root = editorialBasePath.replace(/\/editor$/, ""); return `${root}/${String(path).replace(/^\//, "")}`; }
async function api(path, options = {}) {
  const response = await fetch(apiUrl(path), {...options, headers: {"Content-Type": "application/json", ...(options.headers || {})}});
  const payload = await response.json();
  if (!response.ok) throw new Error(payload.message || payload.error || "Pedido inválido");
  return payload;
}
function actor() { return $("#current-user").value; }
function currentUser() { return overviewData?.users?.find(user => user.username === actor()); }
function n(value) { return Number(value || 0).toLocaleString("pt-PT"); }
function h(value) { return String(value ?? "").replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char])); }
function formatDate(value) { if (!value) return "—"; const parsed = new Date(value.endsWith("Z") || value.includes("+") ? value : `${value}Z`); return Number.isNaN(parsed.valueOf()) ? value : parsed.toLocaleString("pt-PT"); }
function resourceLabel(value) { return value === "dictionary" ? "Dicionário" : "Vocabulário"; }
function roleLabel(value) { return {editor:"Editor",reviewer:"Revisor",approver:"Aprovador",administrator:"Administrador"}[value] || value; }
function workflowLabel(value) { return {IMPORTED:"Importada",EDITING:"Editada",REVIEW:"Revista",VALIDATED:"Aprovada",PUBLISHED:"Publicada"}[value] || value; }
function workflowClass(value) { return {IMPORTED:"workflow-imported",EDITING:"workflow-editing",REVIEW:"workflow-review",VALIDATED:"workflow-validated",PUBLISHED:"workflow-published"}[value] || "workflow-imported"; }
function toast(message, error = false) { const node = $("#toast"); node.textContent = message; node.className = `show${error ? " error" : ""}`; setTimeout(() => { node.className = ""; }, 5000); }

document.querySelectorAll("[data-view]").forEach(button => button.addEventListener("click", () => {
  document.querySelectorAll(".nav-link").forEach(item => item.classList.toggle("active", item === button));
  document.querySelectorAll(".view").forEach(view => view.classList.toggle("active", view.id === button.dataset.view));
  if (button.dataset.view === "governance-panel") loadControlledValues();
  if (button.dataset.view === "entries-panel") loadEntries();
  if (button.dataset.view === "publication-panel") loadPublication();
}));

async function loadOverview() {
  overviewData = await api("/api/editorial/overview");
  const run = overviewData.active_import;
  if (!run) { $("#overview").textContent = "Não existe uma importação ativa."; return; }
  const workflow = Object.fromEntries(overviewData.workflow.map(item => [item.value, item.count]));
  $("#overview").textContent = `${n(run.entry_count)} entradas · ${n(workflow.EDITING)} em edição · ${n(workflow.REVIEW)} em revisão · ${n(workflow.VALIDATED)} validadas`;
  populateUsers(overviewData.users);
  const counts = overviewData.filter_counts;
  countedSelect("#resource-filter", counts.resource, "Dicionário e Vocabulário", run.entry_count, resourceLabel);
  countedSelect("#workflow-filter", completeCounts(counts.workflow, ["IMPORTED","EDITING","REVIEW","VALIDATED","PUBLISHED"]), "Todos", run.entry_count, workflowLabel);
  countedSelect("#source-status-filter", counts.editorial_statuses, "Todos", run.entry_count);
  countedSelect("#grammar-filter", counts.grammar, "Todas", run.entry_count);
  countedSelect("#domain-filter", counts.domains, "Todos", run.entry_count);
  countedSelect("#severity-filter", completeCounts(counts.severity, ["error","warning","info"]), "Todos", run.entry_count, value => ({error:"Erros",warning:"Avisos",info:"Informação"}[value]));
}
function populateUsers(users) {
  const select = $("#current-user");
  const saved = localStorage.getItem("acl-editorial-user") || "editor.demo";
  select.innerHTML = users.map(user => `<option value="${h(user.username)}">${h(user.display_name)} — ${h(roleLabel(user.role))}</option>`).join("");
  select.value = users.some(user => user.username === saved) ? saved : users[0]?.username || "";
  select.onchange = () => { localStorage.setItem("acl-editorial-user", select.value); updateRoleIndicator(); if ($("#governance-panel").classList.contains("active")) loadControlledValues(); if ($("#publication-panel").classList.contains("active")) loadPublicationEntries(); };
  updateRoleIndicator();
}
function updateRoleIndicator() { const role = currentUser()?.role || ""; const node = $("#role-indicator"); node.textContent = roleLabel(role); node.className = `role-indicator role-${role}`; document.body.dataset.editorialRole = role; $("#add-controlled").disabled = !["reviewer","approver","administrator"].includes(role); }
function countedSelect(selector, values = [], first, total, label = value => value) { const select = $(selector); const previous = select.value; select.innerHTML = `<option value="">${h(first)} (${n(total)})</option>` + values.map(item => `<option value="${h(item.value)}">${h(label(item.value))} (${n(item.count)})</option>`).join(""); select.value = previous; }
function completeCounts(items = [], values) { const found = Object.fromEntries(items.map(item => [item.value,item.count])); return values.map(value => ({value,count:found[value] || 0})); }

// Listas controladas
["#controlled-category","#controlled-status","#controlled-sort","#controlled-direction"].forEach(selector => $(selector).addEventListener("change", loadControlledValues));
async function loadControlledValues() {
  const params = new URLSearchParams({category:$("#controlled-category").value,sort:$("#controlled-sort").value,direction:$("#controlled-direction").value});
  if ($("#controlled-status").value) params.set("status", $("#controlled-status").value);
  try {
    const data = await api(`/api/editorial/controlled-values?${params}`); controlledValues = data.items;
    const options = controlledValues.map(item => `<option value="${h(item.value)}"></option>`).join("");
    const locked = ["reviewer","approver","administrator"].includes(currentUser()?.role) ? "" : " disabled";
    $("#controlled-values").innerHTML = `<datalist id="controlled-options">${options}</datalist><table><thead><tr><th>Abreviatura / valor</th><th>Uso</th><th>Descrição completa</th><th>Estado</th><th>Substituição</th><th>Ações</th></tr></thead><tbody>${controlledValues.map(item => `<tr data-cv-row="${item.id}"><td><input data-cv-value="${item.id}" value="${h(item.value)}"${locked}></td><td><strong>${n(item.usage_count)}</strong></td><td><input data-cv-label="${item.id}" value="${h(item.display_label || "")}"${locked}></td><td><select data-cv-status="${item.id}"${locked}><option value="authorized"${item.governance_status === "authorized" ? " selected" : ""}>Autorizado</option><option value="unmapped"${item.governance_status === "unmapped" ? " selected" : ""}>Por mapear</option><option value="obsolete"${item.governance_status === "obsolete" ? " selected" : ""}>Obsoleto</option></select></td><td><input list="controlled-options" data-cv-replacement="${item.id}" value="${h(item.replacement_value || "")}"${locked}></td><td><div class="table-actions"><button class="compact" data-cv-save="${item.id}"${locked}>Gravar</button><button class="danger compact" data-cv-delete="${item.id}"${locked}>Apagar</button></div></td></tr>`).join("")}</tbody></table>`;
    document.querySelectorAll("[data-cv-save]").forEach(node => node.addEventListener("click", () => saveControlledValue(Number(node.dataset.cvSave))));
    document.querySelectorAll("[data-cv-delete]").forEach(node => node.addEventListener("click", () => deleteControlledValue(Number(node.dataset.cvDelete))));
  } catch (error) { $("#controlled-values").textContent = error.message; }
}
async function saveControlledValue(id) {
  const original = controlledValues.find(item => item.id === id); const value = document.querySelector(`[data-cv-value="${id}"]`).value.trim();
  const duplicate = controlledValues.find(item => item.id !== id && item.value.localeCompare(value, "pt", {sensitivity:"base"}) === 0);
  if (duplicate) {
    if (!confirm(`“${value}” já existe. Pretende unir “${original.value}” a esse valor? Os ${n(original.usage_count)} usos serão atualizados.`)) { await loadControlledValues(); toast("Merge recusado; a alteração foi anulada."); return; }
    try { await api("/api/editorial/controlled-values/merge", {method:"POST",body:JSON.stringify({source_id:id,target_id:duplicate.id,actor:actor(),comment:`Merge de ${original.value} em ${duplicate.value}`})}); toast("Valores unidos e entradas atualizadas."); await Promise.all([loadControlledValues(),loadOverview()]); } catch (error) { toast(error.message,true); }
    return;
  }
  try { await api(`/api/editorial/controlled-values/${id}`, {method:"PATCH",body:JSON.stringify({actor:actor(),value,display_label:document.querySelector(`[data-cv-label="${id}"]`).value,governance_status:document.querySelector(`[data-cv-status="${id}"]`).value,replacement_value:document.querySelector(`[data-cv-replacement="${id}"]`).value,comment:"Revisão da lista controlada"})}); toast("Valor atualizado."); await Promise.all([loadControlledValues(),loadOverview()]); } catch (error) { toast(error.message,true); await loadControlledValues(); }
}
$("#add-controlled").addEventListener("click", async () => { const value = prompt("Novo valor ou abreviatura:"); if (!value?.trim()) return; const label = prompt("Descrição completa:") || ""; try { await api("/api/editorial/controlled-values", {method:"POST",body:JSON.stringify({actor:actor(),category:$("#controlled-category").value,value:value.trim(),display_label:label})}); toast("Nova opção adicionada."); loadControlledValues(); } catch (error) { toast(error.message,true); } });
async function deleteControlledValue(id) { const item = controlledValues.find(value => value.id === id); if (!confirm(`Apagar “${item.value}”? Só é possível se não estiver em uso.`)) return; try { await api(`/api/editorial/controlled-values/${id}`, {method:"DELETE",body:JSON.stringify({actor:actor(),comment:"Remoção de valor controlado"})}); toast("Valor apagado."); loadControlledValues(); } catch (error) { toast(error.message,true); } }

// Pesquisa, visualização pública e edição
$("#search-form").addEventListener("submit", event => { event.preventDefault(); setActiveAlphabet(""); loadEntries(); });
document.querySelectorAll("#entries-panel select").forEach(select => select.addEventListener("change", () => loadEntries()));
$("#clear-filters").addEventListener("click", () => { $("#query").value = ""; setActiveAlphabet(""); document.querySelectorAll("#entries-panel select").forEach(select => { select.value = ""; }); loadEntries(); });
async function loadEntries(append = false) {
  if (!append) entryOffset = 0;
  $("#status").textContent = "A pesquisar…"; const params = new URLSearchParams({q:$("#query").value,limit:"100",offset:String(entryOffset)});
  const filters = {"#resource-filter":"resource","#workflow-filter":"workflow","#source-status-filter":"editorial_status","#grammar-filter":"grammar","#domain-filter":"domain","#severity-filter":"severity"};
  Object.entries(filters).forEach(([selector,key]) => { if ($(selector).value) params.set(key,$(selector).value); });
  try { const payload = await api(`/api/editorial/entries?${params}`); const markup = payload.items.map(item => `<button class="result-card ${workflowClass(item.workflow_status)}${item.public_id === selectedId ? " is-selected" : ""}" data-entry-id="${h(item.public_id)}"><span class="result-card__top"><h3>${h(item.lemma || "(sem lema)")}</h3><span class="result-card__source">${h(resourceLabel(item.resource))}</span></span><p class="result-card__grammar">${h(item.grammatical_info || "sem classificação")}</p><small>${h(workflowLabel(item.workflow_status))}${item.error_count ? ` · ${n(item.error_count)} erros` : item.warning_count ? ` · ${n(item.warning_count)} avisos` : ""}</small></button>`).join(""); if (append) $("#entries").insertAdjacentHTML("beforeend",markup); else $("#entries").innerHTML = markup || `<div class="entry-empty"><p>Sem resultados.</p></div>`; entryOffset += payload.items.length; $("#status").textContent = `${n(payload.total)} resultados`; $("#load-more-editorial").hidden = entryOffset >= payload.total; document.querySelectorAll("[data-entry-id]:not([data-bound])").forEach(node => { node.dataset.bound = "true"; node.addEventListener("click", () => showEntry(node.dataset.entryId)); }); } catch (error) { $("#status").textContent = error.message; }
}
$("#load-more-editorial").addEventListener("click", () => loadEntries(true));
$("#editorial-alphabet").innerHTML = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("").map(letter => `<button type="button" data-letter="${letter.toLowerCase()}" aria-pressed="false" title="Mostrar entradas começadas por ${letter}">${letter}</button>`).join("");
function setActiveAlphabet(letter) { activeAlphabet = letter; document.querySelectorAll("[data-letter]").forEach(node => { const active = node.dataset.letter === letter; node.classList.toggle("is-active",active); node.setAttribute("aria-pressed",String(active)); }); $("#alphabet-current").textContent = letter ? `A mostrar entradas começadas por ${letter.toUpperCase()}.` : "A mostrar entradas de todas as letras."; $("#alphabet-all").disabled = !letter; }
document.querySelectorAll("[data-letter]").forEach(node => node.addEventListener("click", () => { $("#query").value = node.dataset.letter; setActiveAlphabet(node.dataset.letter); loadEntries(); }));
$("#alphabet-all").addEventListener("click", () => { $("#query").value = ""; setActiveAlphabet(""); loadEntries(); });
setActiveAlphabet("");
async function showEntry(id) { try { selectedId = id; selectedEntry = await api(`/api/editorial/entries/${encodeURIComponent(id)}`); renderPublicEntry(selectedEntry); document.querySelectorAll("[data-entry-id]").forEach(node => node.classList.toggle("is-selected",node.dataset.entryId===id)); } catch (error) { toast(error.message,true); } }
function renderPublicEntry(item) {
  const entry = item.public_view; const lexical = entry.lexical || {}; let previousSection = null; let index = 0;
  const imageMarkup = images => (images || []).length ? `<div class="entry-images">${images.map(image => `<figure><img src="${publicUrl(`entry-images/${encodeURIComponent(image.url || image.filename || image)}`)}" alt="${h(image.caption || entry.lemma || "Imagem da entrada")}" loading="lazy">${image.caption ? `<figcaption>${h(image.caption)}</figcaption>` : ""}</figure>`).join("")}</div>` : "";
  const senses = (lexical.senses || []).map(sense => {
    index++; let heading = "";
    if (sense.section && sense.section !== previousSection) { heading = `<h4 class="related-heading">${h(sense.section)}</h4>`; previousSection = sense.section; }
    const labels = (sense.labels || []).map(label => `<span class="usage-label">${h(label.label || label.value)}</span>`).join("");
    const examples = (sense.examples || []).map(example => `<blockquote class="example">“${h(example.quote)}”${example.source ? ` <cite>— ${h(example.source)}</cite>` : ""}</blockquote>`).join("");
    const notes = (sense.notes || []).map(note => `<aside class="sense__note">${h(note.value)}</aside>`).join("");
    const references = (sense.references || []).map(ref => `<a href="${publicUrl(`?q=${encodeURIComponent(ref.value)}`)}">${h(ref.value)}</a>`).join(" · ");
    return `${heading}<section class="sense sense--depth-${Math.min(Number(sense.depth)||1,3)}"><span class="sense__number">${h(sense.number || index)}.</span><div>${labels ? `<div class="sense__labels">${labels}</div>` : ""}<p class="sense__definition">${h(sense.definition || "[definição em preparação]")}</p>${examples}${imageMarkup(sense.images)}${notes}${references ? `<div class="reference-list">Ver também: ${references}</div>` : ""}</div></section>`;
  }).join("");
  const glosses = (lexical.gloss_items || []).map(gloss => `<p>${h(gloss.value)}</p>`).join("");
  const variants = (lexical.orthographies || []).map(form => form.value).filter(value => value && value !== entry.lemma);
  const references = (lexical.references || []).map(ref => `<a href="${publicUrl(`?q=${encodeURIComponent(ref.value)}`)}">${h(ref.value)}</a>`).join(" · ");
  const notes = (lexical.notes || []).map(note => `<p class="entry-note">${h(note.value)}</p>`).join("");
  const etymology = (lexical.etymologies || []).map(value => `<div class="etymology">${h(value)}</div>`).join("");
  $("#detail").innerHTML = `<div class="entry-toolbar ${workflowClass(item.workflow_status)}"><div class="entry-toolbar__state"><span class="workflow-pill">${h(workflowLabel(item.workflow_status))}</span><span>${h(item.public_id)}</span></div><button id="edit-entry" type="button">Editar</button></div><header class="entry-header ${workflowClass(item.workflow_status)}"><div class="entry-header__meta"><span class="source-badge">${h(resourceLabel(item.resource))}</span><span class="status-badge">${h(entry.source_status_label || entry.source_status || "Sem estado")}</span></div><div class="entry-title-row"><h2>${h(entry.lemma || "(sem lema)")}</h2><span class="entry-grammar">${h(entry.grammatical_label || entry.grammatical_info || "")}</span></div>${variants.length ? `<p class="entry-variants"><strong>Outras formas:</strong> ${h(variants.join(" · "))}</p>` : ""}</header>${glosses ? `<section class="entry-section entry-gloss"><h3 class="entry-section__title">Enquadramento da entrada</h3>${glosses}</section>` : ""}${imageMarkup(lexical.images)}<section class="entry-section"><h3 class="entry-section__title">${senses ? `Aceções e definições <span>(${lexical.senses.length})</span>` : "Informação ortográfica"}</h3>${senses || "<p>Esta entrada não contém aceções lexicográficas.</p>"}</section>${references ? `<section class="entry-section"><h3 class="entry-section__title">Relações e remissões</h3><div class="reference-list">Ver também: ${references}</div></section>` : ""}${notes ? `<section class="entry-section"><h3 class="entry-section__title">Notas</h3>${notes}</section>` : ""}${etymology ? `<section class="entry-section"><h3 class="entry-section__title">Etimologia</h3>${etymology}</section>` : ""}${renderWorkflow(item)}${renderIssues(item)}${renderDiagnostics(item)}${renderHistory(item)}`;
  $("#edit-entry").addEventListener("click", () => renderEditEntry(item)); bindEntryActions(item);
}
function renderEditEntry(item) {
  const grammarOptions = optionList(overviewData.controlled_options.grammar,item.grammatical_info); const statusOptions = optionList(overviewData.controlled_options.editorial_status,item.editorial_status);
  $("#detail").innerHTML = `<div class="entry-toolbar"><div class="entry-toolbar__state"><span class="workflow-pill">${h(workflowLabel(item.workflow_status))}</span><strong>Modo de edição</strong></div><button id="cancel-edit" class="secondary" type="button">Cancelar</button></div><form id="edit-form" class="edit-form"><div class="edit-grid"><label>Lema<input id="lemma" value="${h(item.lemma)}" required></label><label>Classe gramatical<select id="grammar">${grammarOptions}</select></label><label>Estado da fonte<select id="source-status">${statusOptions}</select></label></div><h3>Formas e variantes (${item.forms.length})</h3><div class="editable-list">${item.forms.map(form => `<label class="inline-field">${h(form.kind || "Forma")}<input data-form-id="${form.id}" value="${h(form.value)}"></label>`).join("") || "<p>Sem formas.</p>"}</div><h3>Aceções e definições (${item.senses.length})</h3>${item.senses.map(sense => `<section class="sense-editor"><strong>Aceção ${h(sense.number_label || sense.position_path)}</strong><textarea data-sense-id="${sense.id}">${h(sense.definition || sense.gloss || "")}</textarea></section>`).join("")}<h3>Marcas e domínios (${item.labels.length})</h3><div class="editable-list">${item.labels.map(label => `<label class="inline-field">${h(label.label_type)}<input data-label-id="${label.id}" value="${h(label.value)}"></label>`).join("") || "<p>Sem valores.</p>"}</div><h3>Relações e remissões (${item.relations.length})</h3><div class="editable-list">${item.relations.map(relation => `<div class="inline-field"><input data-relation-text="${relation.id}" value="${h(relation.target_text || "")}"><input data-relation-target="${relation.id}" value="${h(relation.target_id || "")}" placeholder="Identificador"></div>`).join("") || "<p>Sem remissões.</p>"}</div><label>Nota da revisão<textarea id="comment"></textarea></label><div class="actions"><button type="submit">Gravar alterações</button><button id="reload-entry" class="secondary" type="button">Recarregar</button></div></form>${renderIssues(item)}${renderDiagnostics(item)}${renderHistory(item)}`;
  $("#detail .entry-toolbar").classList.add(workflowClass(item.workflow_status));
  $("#cancel-edit").addEventListener("click", () => renderPublicEntry(item)); $("#reload-entry").addEventListener("click", () => showEntry(item.public_id)); $("#edit-form").addEventListener("submit", event => saveEntry(event,item)); bindEntryActions(item);
}
function optionList(items, selected) { const values = [...items.map(item => item.value)]; if (selected && !values.includes(selected)) values.unshift(selected); return `<option value="">Sem valor</option>` + values.map(value => `<option value="${h(value)}"${value === selected ? " selected" : ""}>${h(value)}</option>`).join(""); }
function renderWorkflow(item) { const targets = {IMPORTED:["EDITING"],EDITING:["REVIEW"],REVIEW:["EDITING","VALIDATED"],VALIDATED:["EDITING"],PUBLISHED:["EDITING"]}[item.workflow_status] || []; return `<div class="workflow-actions"><strong>Workflow:</strong>${targets.map(target => `<button class="secondary" type="button" data-workflow="${target}">${h(target === "REVIEW" ? "Submeter para revisão" : workflowLabel(target))}</button>`).join("")}</div>`; }
function renderIssues(item) { return `<div class="issues">${item.validation_issues.map(issue => `<div class="validation-issue"><strong>${h(issue.severity.toUpperCase())} · ${h(issue.rule_code)}</strong><p>${h(issue.message)}</p>${issue.waiver ? `<small>Dispensado por ${h(issue.waiver.actor)}: ${h(issue.waiver.reason)}</small>` : issue.severity === "error" ? `<button class="secondary compact" type="button" data-waive="${h(issue.rule_code)}">Dispensar com justificação</button>` : ""}</div>`).join("")}</div>`; }
function renderDiagnostics(item) { const projection = {...item}; delete projection.raw_xml; delete projection.revisions; return `<details class="technical-details"><summary>Identificação e metadados técnicos</summary><div class="diagnostic-grid"><pre>${h(JSON.stringify(projection,null,2))}</pre><pre>${h(item.raw_xml)}</pre></div></details>`; }
function renderHistory(item) { return `<details class="history-details"><summary>Histórico e auditoria (${item.revisions.length + item.audit_events.length})</summary><ol class="revisions">${item.revisions.map(rev => `<li>#${rev.revision_no} · ${h(rev.actor || "sem autor")} · ${h(rev.comment || "sem nota")} <button class="secondary compact" data-restore="${rev.revision_no}">Repor</button></li>`).join("")}${item.audit_events.map(event => `<li>${h(event.event_type)} · ${h(event.actor)} · ${h(event.previous_state || "—")} → ${h(event.resulting_state || "—")}</li>`).join("")}</ol></details>`; }
function bindEntryActions(item) { document.querySelectorAll("[data-workflow]").forEach(node => node.addEventListener("click", () => changeWorkflow(item.public_id,node.dataset.workflow))); document.querySelectorAll("[data-restore]").forEach(node => node.addEventListener("click", () => restoreRevision(item.public_id,Number(node.dataset.restore)))); document.querySelectorAll("[data-waive]").forEach(node => node.addEventListener("click", () => waiveIssue(item.public_id,node.dataset.waive))); }
async function saveEntry(event,item) { event.preventDefault(); const submit = event.submitter; submit.disabled = true; try { const updated = await api(`/api/editorial/entries/${encodeURIComponent(item.public_id)}`,{method:"PATCH",body:JSON.stringify({expected_updated_at:item.updated_at,actor:actor(),comment:$("#comment").value,lemma:$("#lemma").value,grammatical_info:$("#grammar").value,editorial_status:$("#source-status").value,forms:[...document.querySelectorAll("[data-form-id]")].map(node => ({id:Number(node.dataset.formId),value:node.value})),senses:[...document.querySelectorAll("[data-sense-id]")].map(node => ({id:Number(node.dataset.senseId),definition:node.value})),labels:[...document.querySelectorAll("[data-label-id]")].map(node => ({id:Number(node.dataset.labelId),value:node.value})),relations:[...document.querySelectorAll("[data-relation-text]")].map(node => ({id:Number(node.dataset.relationText),target_text:node.value,target_id:document.querySelector(`[data-relation-target="${node.dataset.relationText}"]`).value}))})}); selectedEntry=updated; renderPublicEntry(updated); toast("Alterações gravadas; a entrada passou para Em edição."); await Promise.all([loadOverview(),loadEntries()]); } catch(error){toast(error.message,true);} finally{submit.disabled=false;} }
async function changeWorkflow(id,target) { try { const item=await api(`/api/editorial/entries/${encodeURIComponent(id)}/workflow`,{method:"POST",body:JSON.stringify({target,actor:actor(),comment:`Transição para ${target}`})}); selectedEntry=item; renderPublicEntry(item); toast(`Entrada movida para ${workflowLabel(target)}.`); await Promise.all([loadOverview(),loadEntries(),loadPublicationEntries()]); } catch(error){toast(error.message,true);} }
async function restoreRevision(id,revision) { if(!confirm(`Repor a revisão ${revision}?`))return; try{const item=await api(`/api/editorial/entries/${encodeURIComponent(id)}/revisions/${revision}/restore`,{method:"POST",body:JSON.stringify({actor:actor(),comment:`Reposição da revisão ${revision}`})});renderPublicEntry(item);toast("Revisão reposta.");}catch(error){toast(error.message,true);} }
async function waiveIssue(id,rule) { const reason=prompt("Justificação obrigatória para dispensar este erro:");if(reason===null)return;try{const item=await api(`/api/editorial/entries/${encodeURIComponent(id)}/issues/${encodeURIComponent(rule)}/waive`,{method:"POST",body:JSON.stringify({actor:actor(),reason})});renderPublicEntry(item);toast("Erro dispensado para esta versão da entrada.");}catch(error){toast(error.message,true);} }

// Publicação seletiva
async function loadPublicationEntries(){try{const data=await api("/api/editorial/publication-entries?limit=500");publicationItems=data.items;const canSelect=["approver","administrator"].includes(currentUser()?.role);$("#select-visible").disabled=!canSelect;$("#unselect-visible").disabled=!canSelect;$("#publication-selection-summary").textContent=`${n(data.selected)} selecionadas de ${n(data.total)} entradas validadas`;$("#publication-entries").innerHTML=data.items.map(item=>`<label class="publication-entry"><input type="checkbox" data-publication-id="${h(item.public_id)}"${item.selected ? " checked" : ""}${canSelect ? "" : " disabled"}><span><strong>${h(item.lemma)}</strong><small>${h(resourceLabel(item.resource))} · ${h(item.grammatical_info || "sem classe")}</small></span></label>`).join("")||"<p>Não existem entradas validadas à espera de publicação.</p>";document.querySelectorAll("[data-publication-id]").forEach(node=>node.addEventListener("change",()=>setPublicationSelection([node.dataset.publicationId],node.checked)));}catch(error){$("#publication-selection-summary").textContent=error.message;}}
async function setPublicationSelection(ids,selected){if(!ids.length){toast("Não existem entradas visíveis para alterar.");return;}try{await api("/api/editorial/publication-selection",{method:"POST",body:JSON.stringify({public_ids:ids,selected,actor:actor()})});await loadPublicationEntries();}catch(error){toast(error.message,true);await loadPublicationEntries();}}
$("#select-visible").addEventListener("click",()=>setPublicationSelection(publicationItems.map(item=>item.public_id),true));$("#unselect-visible").addEventListener("click",()=>setPublicationSelection(publicationItems.filter(item=>item.selected).map(item=>item.public_id),false));
$("#validate").addEventListener("click",async()=>{const button=$("#validate");button.disabled=true;$("#validation-status").textContent="A validar o corpus…";try{renderValidation(await api("/api/editorial/validate",{method:"POST",body:"{}"}));await loadOverview();}catch(error){toast(error.message,true);}finally{button.disabled=false;}});
function renderValidation(result){$("#validation-status").textContent=`${result.valid ? "Válido" : "Com erros bloqueantes"} · ${n(result.blocking_errors ?? result.errors)} erros · ${n(result.warnings)} avisos`;}
$("#prepare-release").addEventListener("click",async()=>{try{await api("/api/editorial/releases/prepare",{method:"POST",body:JSON.stringify({actor:actor(),description:$("#release-description").value})});publicationTimer=setInterval(loadPublication,1000);loadPublication();}catch(error){toast(error.message,true);}});
async function loadPublication(){try{const [job,validation]=await Promise.all([api("/api/editorial/publish/status"),api("/api/editorial/validation")]);renderValidation(validation);$("#publication-status").textContent=job.message||"Nenhuma operação em curso.";$("#prepare-release").disabled=job.state==="running";renderReleases(job.releases||[],job.active_release);await loadPublicationEntries();if(job.state!=="running"&&publicationTimer){clearInterval(publicationTimer);publicationTimer=null;if(job.state==="succeeded")toast(job.message);if(job.state==="failed")toast(job.message,true);}}catch(error){$("#publication-status").textContent=error.message;}}
function renderReleases(releases,active){$("#releases").innerHTML=`<table><thead><tr><th>Versão</th><th>Estado</th><th>Responsáveis</th><th>Data</th><th>Ações</th></tr></thead><tbody>${releases.map(release=>{const actions=[];if(release.state==="candidate")actions.push(`<button data-release-action="approve" data-release="${h(release.release_id)}">Aprovar</button>`);if(release.state==="approved")actions.push(`<button data-release-action="publish" data-release="${h(release.release_id)}">Publicar</button>`);if(release.state==="archived")actions.push(`<button class="secondary" data-release-action="rollback" data-release="${h(release.release_id)}">Reverter</button>`);return `<tr><td><strong>${h(release.release_id)}</strong>${release.release_id===active?'<br><span class="active-release">Ativa</span>':""}<br><small>${h(release.description||"")}</small></td><td>${h(release.state)}</td><td>${h(release.prepared_by||"—")}<br>${h(release.approved_by||"—")}</td><td>${h(formatDate(release.created_at))}</td><td class="table-actions">${actions.join(" ")}</td></tr>`;}).join("")}</tbody></table>`;document.querySelectorAll("[data-release-action]").forEach(node=>node.addEventListener("click",()=>releaseAction(node.dataset.release,node.dataset.releaseAction)));}
async function releaseAction(id,action){const labels={approve:"aprovar",publish:"publicar",rollback:"reverter para"};if(!confirm(`Confirma que pretende ${labels[action]} ${id}?`))return;try{await api(`/api/editorial/releases/${encodeURIComponent(id)}/${action}`,{method:"POST",body:JSON.stringify({actor:actor(),comment:`${labels[action]} ${id}`})});if(action!=="approve")publicationTimer=setInterval(loadPublication,1000);loadPublication();}catch(error){toast(error.message,true);}}

Promise.all([loadOverview(),loadControlledValues()]).catch(error=>toast(error.message,true));
