from __future__ import annotations

GRAMMAR = {
    "???": "classe por determinar",
    "abrev.": "abreviatura",
    "adj.": "adjetivo",
    "adj. f.": "adjetivo feminino",
    "adj. f. sg. e pl.": "adjetivo feminino singular e plural",
    "adj. m.": "adjetivo masculino",
    "adj. m. e f.": "adjetivo masculino e feminino",
    "adj. m. e f. pl.": "adjetivo masculino e feminino plural",
    "adj. m. e f. sg. e pl.": "adjetivo masculino e feminino singular e plural",
    "adj. m. sg. e pl.": "adjetivo masculino singular e plural",
    "adj. m., f. pl.": "adjetivo masculino feminino plural",
    "adv.": "advérbio",
    "adv. relat.": "advérbio relativo",
    "antr.": "antropónimo",
    "art. def.": "artigo definido",
    "conj.": "conjunção",
    "contr.": "contração",
    "det. e pron. indef.": "determinante e pronome indefinido",
    "det. excl.": "determinante exclamativo",
    "det. indef.": "determinante indefinido",
    "det. relat.": "determinante relativo",
    "elem. adj. de loc.": "elemento adjetival de locução",
    "elem. adv. de loc.": "elemento adverbial de locução",
    "elem. de expr.": "elemento de expressão",
    "elem. de form.": "elemento de formação",
    "elem. de loc.": "elemento de locução",
    "elem. nom. de loc.": "elemento nominal de locução",
    "elem. num. de loc.": "elemento numeral de locução",
    "funç. adj.": "função adjetiva",
    "funç. adv.": "função adverbial",
    "funç. det.": "função de determinante",
    "funç. interj.": "função interjetiva",
    "funç. num. ord.": "função de numeral ordinal",
    "funç. pron.": "função pronominal",
    "funç. subst.": "função substantiva",
    "interj.": "interjeição",
    "loc.": "locução",
    "loc. adv.": "locução adverbial",
    "loc. lat.": "locução latina",
    "n. f.": "nome feminino",
    "n. f. ou m.": "nome feminino ou masculino",
    "n. f. ou m. sg. e pl.": "nome feminino ou masculino singular e plural",
    "n. f. pl.": "nome feminino plural",
    "n. f. sg. e pl.": "nome feminino singular e plural",
    "n. m.": "nome masculino",
    "n. m. e f.": "nome masculino e feminino",
    "n. m. e f. pl.": "nome masculino e feminino plural",
    "n. m. e f. sg. e pl.": "nome masculino e feminino singular e plural",
    "n. m. ou f.": "nome masculino ou feminino",
    "n. m. ou f. pl.": "nome masculino ou feminino plural",
    "n. m. ou f. sg. e pl.": "nome masculino ou feminino singular e plural",
    "n. m. pl.": "nome masculino plural",
    "n. m. sg. e pl.": "nome masculino singular e plural",
    "n. m., f.": "nome masculino feminino",
    "n. m., f. pl.": "nome masculino feminino plural",
    "n. pl.": "nome plural",
    "noun": "nome (etiqueta em inglês)",
    "num.": "numeral",
    "num. card.": "numeral cardinal",
    "num. fracion.": "numeral fracionário",
    "num. mult.": "numeral multiplicativo",
    "num. ord.": "numeral ordinal",
    "prep.": "preposição",
    "pron.": "pronome",
    "pron. dem.": "pronome demonstrativo",
    "pron. indef.": "pronome indefinido",
    "pron. interr.": "pronome interrogativo",
    "pron. pes.": "pronome pessoal",
    "pron. pes. m. e f.": "pronome pessoal masculino e feminino",
    "pron. poss.": "pronome possessivo",
    "pron. relat.": "pronome relativo",
    "símb.": "símbolo",
    "top.": "topónimo",
    "v.": "verbo",
    "v. pron.": "verbo pronominal",
}

DOMAINS = {
    "Acúst.": "Acústica",
    "Aeron.": "Aeronáutica",
    "Agr.": "Agricultura",
    "Anat.": "Anatomia",
    "Antrop.": "Antropologia",
    "Apic.": "Apicultura",
    "Arit.": "Aritmética",
    "Arm.": "Armamento",
    "Arqueol.": "Arqueologia",
    "Arquit.": "Arquitetura",
    "Art. Gráf.": "Artes Gráficas",
    "Art. Pl.": "Artes Plásticas",
    "Artilh.": "Artilharia",
    "Astrol.": "Astrologia",
    "Astron.": "Astronomia",
    "Astronáut.": "Astronáutica",
    "Autom.": "Automobilismo",
    "Bact.": "Bacteriologia",
    "Balíst.": "Balística",
    "Biol.": "Biologia",
    "Bioquím.": "Bioquímica",
    "Biotec.": "Biotecnologia",
    "Bot.": "Botânica",
    "Carn.": "Carnificina",
    "Carp.": "Carpintaria",
    "Cartog.": "Cartografia",
    "Cerâm.": "Cerâmica",
    "Chapel.": "Chapelaria",
    "Cineg.": "Cinegética",
    "Cinem.": "Cinema",
    "Cirurg.": "Cirurgia",
    "Comunic.": "Comunicação",
    "Comérc.": "Comércio",
    "Constr.": "Construção",
    "Contab.": "Contabilidade",
    "Corr.": "Curtumes e correaria",
    "Cosmol.": "Cosmologia",
    "Cristalog.": "Cristalografia",
    "Cronol.": "Cronologia",
    "Cul.": "Culinária",
    "Curt.": "Curtumes",
    "Cutel.": "Cutelaria",
    "Danç.": "Dança",
    "Desp.": "Desporto",
    "Diplom.": "Diplomacia",
    "Dir.": "Direito",
    "Dir. Can.": "Direito Canónico",
    "Dir. Civil": "Direito Civil",
    "Dir. Comerc.": "Direito Comercial",
    "Dir. Fiscal.": "Direito Fiscal",
    "Dir. Intern.": "Direito Internacional",
    "Dir. Marít.": "Direito Marítimo",
    "Ecles.": "Eclesiologia",
    "Ecol.": "Ecologia",
    "Econ.": "Economia",
    "Eletr": "Eletricidade",
    "Eletr.": "Eletricidade",
    "Eletrotéc.": "Eletrotecnia",
    "Eletrón.": "Eletrónica",
    "Embr.": "Embriologia",
    "Encad.": "Encadernação",
    "Eng.": "Engenharia",
    "Enol.": "Enologia",
    "Equit.": "Equitação",
    "Esc.": "Escultura",
    "Esgr.": "Esgrima",
    "Estat.": "Estatística",
    "Stat.": "Estatística",
    "Estrat.": "Estratigrafia",
    "Etnog.": "Etnografia",
    "Etnol.": "Etnologia",
    "Farm.": "Farmácia",
    "Filol.": "Filologia",
    "Filos.": "Filosofia",
    "Fin.": "Finanças",
    "Fisiol.": "Fisiologia",
    "Fonét.": "Fonética",
    "Fort.": "Fortificação",
    "Fot.": "Fotografia",
    "Fut.": "Futebol",
    "Fís.": "Física",
    "Fís. Atóm.": "Física Atómica",
    "Geneal.": "Genealogia",
    "Genét.": "Genética",
    "Geod.": "Geodesia",
    "Geog.": "Geografia",
    "Geol.": "Geologia",
    "Geom.": "Geometria",
    "Gram.": "Gramática",
    "Heráld.": "Heráldica",
    "Hidrog.": "Hidrografia",
    "Hidrául.": "Hidráulica",
    "Hig.": "Higiene",
    "Hist.": "História",
    "Hist. Med.": "História da Medicina",
    "Histol.": "Histologia",
    "Ict.": "Ictiologia",
    "Ind.": "Indústria",
    "Inform.": "Informática",
    "Jur.": "Jurisprudência",
    "Ling.": "Linguística",
    "Literat.": "Literatura",
    "Liturg.": "Liturgia",
    "Lóg.": "Lógica",
    "Mar.": "Marinha",
    "Marc.": "Marcenaria",
    "Mark.": "Marketing",
    "Mat.": "Matemática",
    "Mecân.": "Mecânica",
    "Med.": "Medicina",
    "Med. Leg.": "Medicina Legal",
    "Metal.": "Metalurgia",
    "Meteor.": "Meteorologia",
    "Metrol.": "Metrologia",
    "Mil.": "Militar",
    "Miner.": "Mineralogia",
    "Mitol.": "Mitologia",
    "Métr.": "Métrica",
    "Mús.": "Música",
    "Neur.": "Neurologia",
    "Numism.": "Numismática",
    "Náut.": "Náutica",
    "Ocult.": "Ocultismo",
    "Olar.": "Olaria",
    "Ouriv.": "Ourivesaria",
    "Paleog.": "Paleografia",
    "Paleont.": "Paleontologia",
    "Parasit.": "Parasitologia",
    "Pat.": "Patologia",
    "Pec.": "Pecuária",
    "Pedag.": "Pedagogia",
    "Pesc.": "Pesca",
    "Petrol.": "Petrologia",
    "Pisc.": "Piscicultura",
    "Polít.": "Política",
    "Psican.": "Psicanálise",
    "Psicofisiol.": "Psicofisiologia",
    "Psicol.": "Psicologia",
    "Psiq.": "Psiquiatria",
    "Pub.": "Publicidade",
    "Quím.": "Química",
    "Radiol.": "Radiologia",
    "Rel.": "Religião",
    "Retór.": "Retórica",
    "Sal.": "Salinicultura",
    "Serr.": "Serralharia",
    "Sider.": "Siderurgia",
    "Silv.": "Silvicultura",
    "Sociol.": "Sociologia",
    "Tanoar.": "Tanoaria",
    "Taurom.": "Tauromaquia",
    "Teat.": "Teatro",
    "Tecnol.": "Tecnologia",
    "Telecom.": "Telecomunicações",
    "Teleg.": "Telegrafia",
    "Teol.": "Teologia",
    "Teos.": "Teosofia",
    "Terat.": "Teratologia",
    "Tip.": "Tipografia",
    "Topog.": "Topografia",
    "Trigon.": "Trigonometria",
    "TV": "Televisão",
    "Veter.": "Veterinária",
    "Vin.": "Vinicultura",
    "Vit.": "Viticultura",
    "Zool.": "Zoologia",
    "Zootec.": "Zootecnia",
    "Álg.": "Álgebra",
    "Ética.": "Ética",
    "Ópt.": "Óptica",
}

STATUSES = {
    "imported": "importada",
    "draft": "em preparação",
    "new": "nova",
    "edited": "editada",
    "reviewed": "revista editorialmente",
    "validated": "validada",
    "revised": "revisada",
    "needs revision": "precisa de revisão",
}

USAGE_MARKS = {
    "Fig.": "Figurado",
    "Pop.": "Popular",
    "Fam.": "Familiar",
    "Pej.": "Pejorativo",
    "Deprec.": "Depreciativo",
    "Desus.": "Desusado",
    "Ant.": "Antigo",
    "P. us.": "Pouco usado",
}


def grammar_label(value: str | None) -> str | None:
    return _expanded(value, GRAMMAR)


def domain_label(value: str | None) -> str | None:
    return _expanded(value, DOMAINS)


def status_label(value: str | None) -> str | None:
    return _expanded(value, STATUSES)


def usage_label(value: str | None, kind: str | None = None) -> str | None:
    if kind in {"dom", "domain"}:
        return domain_label(value)
    return _expanded(value, USAGE_MARKS)


def _expanded(value: str | None, catalogue: dict[str, str]) -> str | None:
    if not value:
        return value
    expansion = catalogue.get(value)
    return f"{value} ({expansion})" if expansion else value
